// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:         string;
  type:       string;
  place_type: string[];
  relevance:  number;
  properties: Properties;
  text:       string;
  place_name: string;
  center:     number[];
  geometry:   Geometry;
  context:    Context[];
  bbox?:      number[];
}

export interface Context {
  id:          string;
  mapbox_id:   string;
  wikidata?:   string;
  text:        string;
  short_code?: ShortCode;
}

export enum ShortCode {
  Us = "us",
  UsNj = "US-NJ",
  UsNy = "US-NY",
}

export interface Geometry {
  coordinates: number[];
  type:        string;
}

export interface Properties {
  foursquare?: string;
  landmark?:   boolean;
  address?:    string;
  category?:   string;
  mapbox_id?:  string;
}
